version: '3.8'

services:
  postgres:
    image: postgres:13
    container_name: postgres
    environment:
      - POSTGRES_USER=airflow
      - POSTGRES_PASSWORD=airflow
      - POSTGRES_DB=airflow
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U airflow"]
      interval: 5s
      timeout: 5s
      retries: 5
    restart: on-failure

  airflow-webserver:
    build:
      context: .
      dockerfile: Dockerfile.airflow
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - "8080:8080"
    volumes:
      - ./dags:/opt/airflow/dags
      - ./scripts:/opt/airflow/scripts
      - ./raw_data:/opt/airflow/raw_data
      - ./silver_data:/opt/airflow/silver_data
      - ./gold_data:/opt/airflow/gold_data
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - AIRFLOW_VAR_RAW_DATA_PATH=/opt/airflow/raw_data
      - AIRFLOW_VAR_SILVER_DATA_PATH=/opt/airflow/silver_data
      - AIRFLOW_VAR_GOLD_DATA_PATH=/opt/airflow/gold_data
      - AIRFLOW__CORE__EXECUTOR=LocalExecutor
      - AIRFLOW__CORE__SQL_ALCHEMY_CONN=postgresql+psycopg2://airflow:airflow@postgres/airflow
      - AIRFLOW__WEBSERVER__SECRET_KEY=mi-clave-secreta
      - AIRFLOW_UID=50000
    command: >
      bash -c "airflow db init && 
      airflow users create --username admin --firstname admin --lastname admin --role Admin --email admin@example.com --password admin && 
      exec airflow webserver"
    healthcheck:
      test: ["CMD-SHELL", "[ -f /opt/airflow/airflow-webserver.pid ]"]
      interval: 30s
      timeout: 30s
      retries: 3
    restart: always

  airflow-scheduler:
    build:
      context: .
      dockerfile: Dockerfile.airflow
    depends_on:
      airflow-webserver:
        condition: service_healthy
    volumes:
      - ./dags:/opt/airflow/dags
      - ./scripts:/opt/airflow/scripts
      - ./raw_data:/opt/airflow/raw_data
      - ./silver_data:/opt/airflow/silver_data
      - ./gold_data:/opt/airflow/gold_data
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - AIRFLOW_VAR_RAW_DATA_PATH=/opt/airflow/raw_data
      - AIRFLOW_VAR_SILVER_DATA_PATH=/opt/airflow/silver_data
      - AIRFLOW_VAR_GOLD_DATA_PATH=/opt/airflow/gold_data
      - AIRFLOW__CORE__EXECUTOR=LocalExecutor
      - AIRFLOW__CORE__SQL_ALCHEMY_CONN=postgresql+psycopg2://airflow:airflow@postgres/airflow
      - AIRFLOW__WEBSERVER__SECRET_KEY=mi-clave-secreta
      - AIRFLOW_UID=50000
    command: scheduler
    restart: always
    
  jupyter-notebook:
    build:
      context: .
      dockerfile: Dockerfile.jupyter
    container_name: jupyter-notebook
    ports:
      - "8888:8888"
    volumes:
      - ./notebooks:/app/notebooks
      - ./silver_data:/app/silver_data
      - ./gold_data:/app/gold_data
    working_dir: /app/notebooks
    depends_on:
      - airflow-webserver
      - airflow-scheduler

