FROM python:3.9-slim

WORKDIR /app

RUN pip install --no-cache-dir jupyterlab pandas matplotlib pyarrow

RUN mkdir -p /app/notebooks

EXPOSE 8888

CMD ["jupyter-lab", "--ip=0.0.0.0", "--allow-root", "--no-browser", "--NotebookApp.token=''"]