name: Pipeline ETL CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # --- CORRECCIÓN AQUÍ: Usamos la ruta completa de docker-compose ---
      - name: Start Docker Compose
        run: /usr/local/bin/docker-compose -f Avance2_3_4/docker-compose.yml up --build -d

      - name: Wait for Postgres to be ready
        run: sleep 20

      - name: Run Ingest Data Task
        run: /usr/local/bin/docker-compose -f Avance2_3_4/docker-compose.yml run --rm airflow-ingest

      - name: Run Transform Data Task
        run: /usr/local/bin/docker-compose -f Avance2_3_4/docker-compose.yml run --rm airflow-transform
      
      - name: Set up Python for tests
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pandas pyarrow

      - name: Run data validation tests
        run: python Avance2_3_4/test_pipeline.py

      # --- CORRECCIÓN AQUÍ: Usamos la ruta completa de docker-compose ---
      - name: Clean up Docker containers
        if: always()
        run: /usr/local/bin/docker-compose -f Avance2_3_4/docker-compose.yml down
